DROP TABLE IF EXISTS db_1702.ip;
CREATE TABLE db_1702.ip(
  id  INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID pk',
  min  VARCHAR(255) COMMENT '起始IP地址',
  max  VARCHAR(255) COMMENT '终止IP地址',
  geo  VARCHAR(255) COMMENT '地理位置'
);
  SELECT *
  FROM db_1702.ip;

TRUNCATE TABLE db_1702.ip;

SHOW TABLES FROM db_1702;
SELECT count(*)
FROM db_1702.ip
WHERE geo REGEXP '拉萨市';